# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mess', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FileRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=200)),
                ('dep', models.CharField(max_length=200)),
                ('filename', models.CharField(default='MCAData.csv', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='newregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('pub', models.CharField(max_length=200)),
                ('pri', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='vis', max_length=200)),
                ('utype', models.CharField(default='HOD', max_length=200)),
                ('email', models.CharField(default='vis@gmail.com', max_length=200)),
                ('uid', models.CharField(default='12345', max_length=200)),
                ('dep', models.CharField(default='MCA', max_length=200)),
                ('mob', models.CharField(default='9874563210', max_length=200)),
                ('username', models.CharField(default='vis', max_length=200, unique=True)),
                ('password', models.CharField(default='vis', max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(default='[1,1,1,1,1,1]', max_length=200)),
                ('dep', models.CharField(default='MCA', max_length=200)),
                ('filename', models.CharField(default='MCAData.csv', max_length=200)),
            ],
        ),
    ]
